2025-03-04 23:33:30.498 | ERROR    | mcp_test_harness.app:list_tools:26 - Error listing tools: 'NoneType' object is not subscriptable
2025-03-04 23:33:30.504 | ERROR    | mcp_test_harness.app:call_tool:67 - Tool call failed
Traceback (most recent call last):

  File "/home/persona/.cache/pypoetry/virtualenvs/mcp-test-harness-CndvWiBk-py3.11/bin/pytest", line 8, in <module>
    sys.exit(console_main())
    │   │    └ <function console_main at 0x7fdf073d8e00>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/home/persona/.cache/pypoetry/virtualenvs/mcp-test-harness-CndvWiBk-py3.11/lib/python3.11/site-packages/_pytest/config/__init__.py", line 201, in console_main
    code = main()
           └ <function main at 0x7fdf073d8d60>
  File "/home/persona/.cache/pypoetry/virtualenvs/mcp-test-harness-CndvWiBk-py3.11/lib/python3.11/site-packages/_pytest/config/__init__.py", line 175, in main
    ret: ExitCode | int = config.hook.pytest_cmdline_main(config=config)
         │                │      │    │                          └ <_pytest.config.Config object at 0x7fdf070b2a50>
         │                │      │    └ <HookCaller 'pytest_cmdline_main'>
         │                │      └ <_pytest.config.compat.PathAwareHookProxy object at 0x7fdf070b2490>
         │                └ <_pytest.config.Config object at 0x7fdf070b2a50>
         └ <enum 'ExitCode'>
  File "/home/persona/.cache/pypoetry/virtualenvs/mcp-test-harness-CndvWiBk-py3.11/lib/python3.11/site-packages/pluggy/_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           │    │         │    │     │    │                  │       └ True
           │    │         │    │     │    │                  └ {'config': <_pytest.config.Config object at 0x7fdf070b2a50>}
           │    │         │    │     │    └ <member '_hookimpls' of 'HookCaller' objects>
           │    │         │    │     └ <HookCaller 'pytest_cmdline_main'>
           │    │         │    └ <member 'name' of 'HookCaller' objects>
           │    │         └ <HookCaller 'pytest_cmdline_main'>
           │    └ <member '_hookexec' of 'HookCaller' objects>
           └ <HookCaller 'pytest_cmdline_main'>
  File "/home/persona/.cache/pypoetry/virtualenvs/mcp-test-harness-CndvWiBk-py3.11/lib/python3.11/site-packages/pluggy/_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'config': <_pytest.config.Config object at 0x7fdf070b2a50>}
           │    │               │          └ [<HookImpl plugin_name='main', plugin=<module '_pytest.main' from '/home/persona/.cache/pypoetry/virtualenvs/mcp-test-harness...
           │    │               └ 'pytest_cmdline_main'
           │    └ <function _multicall at 0x7fdf07ac85e0>
           └ <_pytest.config.PytestPluginManager object at 0x7fdf07275dd0>
  File "/home/persona/.cache/pypoetry/virtualenvs/mcp-test-harness-CndvWiBk-py3.11/lib/python3.11/site-packages/pluggy/_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<_pytest.config.Config object at 0x7fdf070b2a50>]
          │         └ <member 'function' of 'HookImpl' objects>
          └ <HookImpl plugin_name='main', plugin=<module '_pytest.main' from '/home/persona/.cache/pypoetry/virtualenvs/mcp-test-harness-...
  File "/home/persona/.cache/pypoetry/virtualenvs/mcp-test-harness-CndvWiBk-py3.11/lib/python3.11/site-packages/_pytest/main.py", line 330, in pytest_cmdline_main
    return wrap_session(config, _main)
           │            │       └ <function _main at 0x7fdf07266840>
           │            └ <_pytest.config.Config object at 0x7fdf070b2a50>
           └ <function wrap_session at 0x7fdf07266700>
  File "/home/persona/.cache/pypoetry/virtualenvs/mcp-test-harness-CndvWiBk-py3.11/lib/python3.11/site-packages/_pytest/main.py", line 283, in wrap_session
    session.exitstatus = doit(config, session) or 0
    │       │            │    │       └ <Session  exitstatus=<ExitCode.OK: 0> testsfailed=2 testscollected=9>
    │       │            │    └ <_pytest.config.Config object at 0x7fdf070b2a50>
    │       │            └ <function _main at 0x7fdf07266840>
    │       └ <ExitCode.OK: 0>
    └ <Session  exitstatus=<ExitCode.OK: 0> testsfailed=2 testscollected=9>
  File "/home/persona/.cache/pypoetry/virtualenvs/mcp-test-harness-CndvWiBk-py3.11/lib/python3.11/site-packages/_pytest/main.py", line 337, in _main
    config.hook.pytest_runtestloop(session=session)
    │      │    │                          └ <Session  exitstatus=<ExitCode.OK: 0> testsfailed=2 testscollected=9>
    │      │    └ <HookCaller 'pytest_runtestloop'>
    │      └ <_pytest.config.compat.PathAwareHookProxy object at 0x7fdf070b2490>
    └ <_pytest.config.Config object at 0x7fdf070b2a50>
  File "/home/persona/.cache/pypoetry/virtualenvs/mcp-test-harness-CndvWiBk-py3.11/lib/python3.11/site-packages/pluggy/_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           │    │         │    │     │    │                  │       └ True
           │    │         │    │     │    │                  └ {'session': <Session  exitstatus=<ExitCode.OK: 0> testsfailed=2 testscollected=9>}
           │    │         │    │     │    └ <member '_hookimpls' of 'HookCaller' objects>
           │    │         │    │     └ <HookCaller 'pytest_runtestloop'>
           │    │         │    └ <member 'name' of 'HookCaller' objects>
           │    │         └ <HookCaller 'pytest_runtestloop'>
           │    └ <member '_hookexec' of 'HookCaller' objects>
           └ <HookCaller 'pytest_runtestloop'>
  File "/home/persona/.cache/pypoetry/virtualenvs/mcp-test-harness-CndvWiBk-py3.11/lib/python3.11/site-packages/pluggy/_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'session': <Session  exitstatus=<ExitCode.OK: 0> testsfailed=2 testscollected=9>}
           │    │               │          └ [<HookImpl plugin_name='main', plugin=<module '_pytest.main' from '/home/persona/.cache/pypoetry/virtualenvs/mcp-test-harness...
           │    │               └ 'pytest_runtestloop'
           │    └ <function _multicall at 0x7fdf07ac85e0>
           └ <_pytest.config.PytestPluginManager object at 0x7fdf07275dd0>
  File "/home/persona/.cache/pypoetry/virtualenvs/mcp-test-harness-CndvWiBk-py3.11/lib/python3.11/site-packages/pluggy/_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Session  exitstatus=<ExitCode.OK: 0> testsfailed=2 testscollected=9>]
          │         └ <member 'function' of 'HookImpl' objects>
          └ <HookImpl plugin_name='main', plugin=<module '_pytest.main' from '/home/persona/.cache/pypoetry/virtualenvs/mcp-test-harness-...
  File "/home/persona/.cache/pypoetry/virtualenvs/mcp-test-harness-CndvWiBk-py3.11/lib/python3.11/site-packages/_pytest/main.py", line 362, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
    │    │                                        │              └ <Function test_load_server_config>
    │    │                                        └ <Coroutine test_call_tool>
    │    └ <member 'config' of 'Node' objects>
    └ <Coroutine test_call_tool>
  File "/home/persona/.cache/pypoetry/virtualenvs/mcp-test-harness-CndvWiBk-py3.11/lib/python3.11/site-packages/pluggy/_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           │    │         │    │     │    │                  │       └ True
           │    │         │    │     │    │                  └ {'item': <Coroutine test_call_tool>, 'nextitem': <Function test_load_server_config>}
           │    │         │    │     │    └ <member '_hookimpls' of 'HookCaller' objects>
           │    │         │    │     └ <HookCaller 'pytest_runtest_protocol'>
           │    │         │    └ <member 'name' of 'HookCaller' objects>
           │    │         └ <HookCaller 'pytest_runtest_protocol'>
           │    └ <member '_hookexec' of 'HookCaller' objects>
           └ <HookCaller 'pytest_runtest_protocol'>
  File "/home/persona/.cache/pypoetry/virtualenvs/mcp-test-harness-CndvWiBk-py3.11/lib/python3.11/site-packages/pluggy/_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'item': <Coroutine test_call_tool>, 'nextitem': <Function test_load_server_config>}
           │    │               │          └ [<HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from '/home/persona/.cache/pypoetry/virtualenvs/mcp-test-har...
           │    │               └ 'pytest_runtest_protocol'
           │    └ <function _multicall at 0x7fdf07ac85e0>
           └ <_pytest.config.PytestPluginManager object at 0x7fdf07275dd0>
  File "/home/persona/.cache/pypoetry/virtualenvs/mcp-test-harness-CndvWiBk-py3.11/lib/python3.11/site-packages/pluggy/_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Coroutine test_call_tool>, <Function test_load_server_config>]
          │         └ <member 'function' of 'HookImpl' objects>
          └ <HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from '/home/persona/.cache/pypoetry/virtualenvs/mcp-test-harn...
  File "/home/persona/.cache/pypoetry/virtualenvs/mcp-test-harness-CndvWiBk-py3.11/lib/python3.11/site-packages/_pytest/runner.py", line 113, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
    │               │              └ <Function test_load_server_config>
    │               └ <Coroutine test_call_tool>
    └ <function runtestprotocol at 0x7fdf072659e0>
  File "/home/persona/.cache/pypoetry/virtualenvs/mcp-test-harness-CndvWiBk-py3.11/lib/python3.11/site-packages/_pytest/runner.py", line 132, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
    │       │      │               │             └ True
    │       │      │               └ <Coroutine test_call_tool>
    │       │      └ <function call_and_report at 0x7fdf07265e40>
    │       └ <method 'append' of 'list' objects>
    └ [<TestReport 'tests/test_app.py::test_call_tool' when='setup' outcome='passed'>]
  File "/home/persona/.cache/pypoetry/virtualenvs/mcp-test-harness-CndvWiBk-py3.11/lib/python3.11/site-packages/_pytest/runner.py", line 241, in call_and_report
    call = CallInfo.from_call(
           │        └ <classmethod(<function CallInfo.from_call at 0x7fdf07266160>)>
           └ <class '_pytest.runner.CallInfo'>
  File "/home/persona/.cache/pypoetry/virtualenvs/mcp-test-harness-CndvWiBk-py3.11/lib/python3.11/site-packages/_pytest/runner.py", line 341, in from_call
    result: TResult | None = func()
            │                └ <function call_and_report.<locals>.<lambda> at 0x7fdea9aea660>
            └ +TResult
  File "/home/persona/.cache/pypoetry/virtualenvs/mcp-test-harness-CndvWiBk-py3.11/lib/python3.11/site-packages/_pytest/runner.py", line 242, in <lambda>
    lambda: runtest_hook(item=item, **kwds), when=when, reraise=reraise
            │                 │       └ {}
            │                 └ <Coroutine test_call_tool>
            └ <HookCaller 'pytest_runtest_call'>
  File "/home/persona/.cache/pypoetry/virtualenvs/mcp-test-harness-CndvWiBk-py3.11/lib/python3.11/site-packages/pluggy/_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           │    │         │    │     │    │                  │       └ False
           │    │         │    │     │    │                  └ {'item': <Coroutine test_call_tool>}
           │    │         │    │     │    └ <member '_hookimpls' of 'HookCaller' objects>
           │    │         │    │     └ <HookCaller 'pytest_runtest_call'>
           │    │         │    └ <member 'name' of 'HookCaller' objects>
           │    │         └ <HookCaller 'pytest_runtest_call'>
           │    └ <member '_hookexec' of 'HookCaller' objects>
           └ <HookCaller 'pytest_runtest_call'>
  File "/home/persona/.cache/pypoetry/virtualenvs/mcp-test-harness-CndvWiBk-py3.11/lib/python3.11/site-packages/pluggy/_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ False
           │    │               │          │        └ {'item': <Coroutine test_call_tool>}
           │    │               │          └ [<HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from '/home/persona/.cache/pypoetry/virtualenvs/mcp-test-har...
           │    │               └ 'pytest_runtest_call'
           │    └ <function _multicall at 0x7fdf07ac85e0>
           └ <_pytest.config.PytestPluginManager object at 0x7fdf07275dd0>
  File "/home/persona/.cache/pypoetry/virtualenvs/mcp-test-harness-CndvWiBk-py3.11/lib/python3.11/site-packages/pluggy/_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Coroutine test_call_tool>]
          │         └ <member 'function' of 'HookImpl' objects>
          └ <HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from '/home/persona/.cache/pypoetry/virtualenvs/mcp-test-harn...
  File "/home/persona/.cache/pypoetry/virtualenvs/mcp-test-harness-CndvWiBk-py3.11/lib/python3.11/site-packages/_pytest/runner.py", line 174, in pytest_runtest_call
    item.runtest()
    │    └ <function Coroutine.runtest at 0x7fdf06e5b1a0>
    └ <Coroutine test_call_tool>
  File "/home/persona/.cache/pypoetry/virtualenvs/mcp-test-harness-CndvWiBk-py3.11/lib/python3.11/site-packages/pytest_asyncio/plugin.py", line 533, in runtest
    super().runtest()
  File "/home/persona/.cache/pypoetry/virtualenvs/mcp-test-harness-CndvWiBk-py3.11/lib/python3.11/site-packages/_pytest/python.py", line 1627, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
    │    │                                   └ <Coroutine test_call_tool>
    │    └ <property object at 0x7fdf073c7c40>
    └ <Coroutine test_call_tool>
  File "/home/persona/.cache/pypoetry/virtualenvs/mcp-test-harness-CndvWiBk-py3.11/lib/python3.11/site-packages/pluggy/_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           │    │         │    │     │    │                  │       └ True
           │    │         │    │     │    │                  └ {'pyfuncitem': <Coroutine test_call_tool>}
           │    │         │    │     │    └ <member '_hookimpls' of 'HookCaller' objects>
           │    │         │    │     └ <HookCaller 'pytest_pyfunc_call'>
           │    │         │    └ <member 'name' of 'HookCaller' objects>
           │    │         └ <HookCaller 'pytest_pyfunc_call'>
           │    └ <member '_hookexec' of 'HookCaller' objects>
           └ <HookCaller 'pytest_pyfunc_call'>
  File "/home/persona/.cache/pypoetry/virtualenvs/mcp-test-harness-CndvWiBk-py3.11/lib/python3.11/site-packages/pluggy/_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'pyfuncitem': <Coroutine test_call_tool>}
           │    │               │          └ [<HookImpl plugin_name='python', plugin=<module '_pytest.python' from '/home/persona/.cache/pypoetry/virtualenvs/mcp-test-har...
           │    │               └ 'pytest_pyfunc_call'
           │    └ <function _multicall at 0x7fdf07ac85e0>
           └ <_pytest.config.PytestPluginManager object at 0x7fdf07275dd0>
  File "/home/persona/.cache/pypoetry/virtualenvs/mcp-test-harness-CndvWiBk-py3.11/lib/python3.11/site-packages/pluggy/_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Coroutine test_call_tool>]
          │         └ <member 'function' of 'HookImpl' objects>
          └ <HookImpl plugin_name='python', plugin=<module '_pytest.python' from '/home/persona/.cache/pypoetry/virtualenvs/mcp-test-harn...
  File "/home/persona/.cache/pypoetry/virtualenvs/mcp-test-harness-CndvWiBk-py3.11/lib/python3.11/site-packages/_pytest/python.py", line 159, in pytest_pyfunc_call
    result = testfunction(**testargs)
             │              └ {}
             └ <function test_call_tool at 0x7fdea9ae9da0>
  File "/home/persona/.cache/pypoetry/virtualenvs/mcp-test-harness-CndvWiBk-py3.11/lib/python3.11/site-packages/pytest_asyncio/plugin.py", line 1052, in inner
    _loop.run_until_complete(task)
    │     │                  └ <Task pending name='Task-5' coro=<test_call_tool() running at /home/persona/analysis/mcp-client-webapp/tests/test_app.py:61> ...
    │     └ <function BaseEventLoop.run_until_complete at 0x7fdf06de0040>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/home/persona/.pyenv/versions/3.11.11/lib/python3.11/asyncio/base_events.py", line 641, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x7fdf06d9bf60>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/home/persona/.pyenv/versions/3.11.11/lib/python3.11/asyncio/base_events.py", line 608, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x7fdf06de1da0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/home/persona/.pyenv/versions/3.11.11/lib/python3.11/asyncio/base_events.py", line 1936, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x7fdf06f52520>
    └ <Handle <TaskStepMethWrapper object at 0x7fdeab4ffd60>()>
  File "/home/persona/.pyenv/versions/3.11.11/lib/python3.11/asyncio/events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x7fdeab4ffd60>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskStepMethWrapper object at 0x7fdeab4ffd60>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x7fdeab4ffd60>()>

  File "/home/persona/analysis/mcp-client-webapp/tests/test_app.py", line 61, in test_call_tool
    result = await call_tool("test-server", "test-tool", '{"arg1": "value1"}')
                   └ <function call_tool at 0x7fdeaa371c60>

> File "/home/persona/analysis/mcp-client-webapp/mcp_test_harness/app.py", line 53, in call_tool
    server_parameters[server_name],
    │                 └ 'test-server'
    └ None

TypeError: 'NoneType' object is not subscriptable
2025-03-04 23:33:30.534 | INFO     | mcp_test_harness.config:load_server_config:15 - Loaded server config from /tmp/pytest-of-persona/pytest-0/test_load_server_config0/test_config.json
2025-03-04 23:33:30.535 | INFO     | mcp_test_harness.config:create_server_parameters:48 - Created server parameters for test-server
2025-03-04 23:33:30.536 | ERROR    | mcp_test_harness.config:load_server_config:9 - Config file not found: nonexistent_file.json
2025-03-04 23:33:30.543 | INFO     | mcp_test_harness.mcp_client:list_server_tools:23 - Listed 0 tools from test-server
